blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Fragen & Diskussionen
    url: https://github.com/T-Boyke/[REPO_NAME]/discussions
    about: Bitte stelle Fragen hier, anstatt ein Issue zu Ã¶ffnen.
  - name: ğŸ” SicherheitslÃ¼cke melden
    url: https://github.com/T-Boyke/[REPO_NAME]/security/advisories/new
    about: Bitte melde SicherheitslÃ¼cken nicht Ã¶ffentlich.
